// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOjFfpn2PL0E0-62vDe266WbiQLWsjb94',
    appId: '1:996507228247:web:2d62201594b9515baf2b12',
    messagingSenderId: '996507228247',
    projectId: 'passionpals-bc445',
    authDomain: 'passionpals-bc445.firebaseapp.com',
    storageBucket: 'passionpals-bc445.appspot.com',
    measurementId: 'G-35ZE6X5LB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJQoZ15irQfREeB97QTdWp3ixLG4xowM',
    appId: '1:996507228247:android:6f6da367c2eae0e8af2b12',
    messagingSenderId: '996507228247',
    projectId: 'passionpals-bc445',
    storageBucket: 'passionpals-bc445.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGcYoZTlqCUVMB4YyJFPK91VbiOd9QLAQ',
    appId: '1:996507228247:ios:ece12d615ddb6af1af2b12',
    messagingSenderId: '996507228247',
    projectId: 'passionpals-bc445',
    storageBucket: 'passionpals-bc445.appspot.com',
    iosBundleId: 'com.example.passionpals',
  );
}
